default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: graphql_test_development

test:
  <<: *default
  database: graphql_test_test

production:
  <<: *default
  database: graphql_test_production
  username: graphql_test
  password: <%= ENV['GRAPHQL_TEST_DATABASE_PASSWORD'] %>
